In [62]:
import numpy as np

In [63]:
np.random.seed(1)

In [64]:
def relu(x):
    return (x>0)*x

In [65]:
alpha=0.2
hidden_size=4
streetlights=np.array([[1,0,1],[0,1,1],[0,0,1],[1,1,1]])

In [66]:
streetlights

array([[1, 0, 1],
       [0, 1, 1],
       [0, 0, 1],
       [1, 1, 1]])

In [67]:
walk_vs_stop=np.array([1,1,0,0]).T

In [68]:
walk_vs_stop

array([1, 1, 0, 0])

In [69]:
weights_0_1 = 2*np.random.random((3,hidden_size)) - 1


In [70]:
weights_0_1

array([[-0.16595599,  0.44064899, -0.99977125, -0.39533485],
       [-0.70648822, -0.81532281, -0.62747958, -0.30887855],
       [-0.20646505,  0.07763347, -0.16161097,  0.370439  ]])

In [71]:
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1

In [72]:
weights_1_2

array([[-0.5910955 ],
       [ 0.75623487],
       [-0.94522481],
       [ 0.34093502]])

In [73]:
layer_0 = streetlights[0]

In [80]:
output = np.dot(layer_0,weights_0_1)
layer_1=relu(output)
layer_2 = np.dot(layer_1,weights_1_2)

In [81]:
output

array([-0.37242104,  0.51828245, -1.16138222, -0.02489585])

In [82]:
layer_1

array([-0.        ,  0.51828245, -0.        , -0.        ])

In [83]:
layer_2

array([0.39194327])